version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cb_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cb_demo
    ports:
      - "5432:5432"
